spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutti_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: dev_tutti
    password: dEv_tvtt1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /api/basic
      default-page-size: 10000000

jwt:
  expirationTime: 3600000
  secret: 14E0277BCDC57D5763C356A93B2388D50B8E65258BA7862FBD7989202CA077C9