spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutti_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /api/basic
      default-page-size: 10000000